
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: upc.edu
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: fis
    Domain: fis.upc.edu
    Template:
      Count: 3
    Users:
      Count: 1

 - Name: mat
    Domain: mat.upc.edu
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: dac
    Domain: dac.upc.edu
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: entel
    Domain: entel.upc.edu
    Template:
      Count: 2
    Users:
      Count: 1